In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [31]:
ratings = pd.read_csv('../data/ratings.csv')
books_data = pd.read_csv('../data/books.csv')

In [32]:
ratings.head()

   book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [33]:
books_data.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [34]:
#Look for NaN's
ratings.apply(lambda x: x.isnull().sum(),axis=0)

book_id    0
user_id    0
rating     0
dtype: int64

In [35]:
books = pd.DataFrame(books_data, columns=['book_id', 'authors', 'title', 'average_rating','ratings_count', 'image_url'])
books.head()

,book_id,authors,title,average_rating,ratings_count,image_url
0,2767052,Suzanne Collins,"The Hunger Games (The Hunger Games, #1)",4.34,4780653,https://images.gr-assets.com/books/1447303603m...
1,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,https://images.gr-assets.com/books/1474154022m...
2,41865,Stephenie Meyer,"Twilight (Twilight, #1)",3.57,3866839,https://images.gr-assets.com/books/1361039443m...
3,2657,Harper Lee,To Kill a Mockingbird,4.25,3198671,https://images.gr-assets.com/books/1361975680m...
4,4671,F. Scott Fitzgerald,The Great Gatsby,3.89,2683664,https://images.gr-assets.com/books/1490528560m...

In [36]:
books_info = pd.merge(books, ratings, on='book_id')
books_info.head()

,book_id,authors,title,average_rating,ratings_count,image_url,user_id,rating
0,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,https://images.gr-assets.com/books/1474154022m...,314,3
1,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,https://images.gr-assets.com/books/1474154022m...,588,1
2,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,https://images.gr-assets.com/books/1474154022m...,2077,2
3,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,https://images.gr-assets.com/books/1474154022m...,2487,3
4,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,https://images.gr-assets.com/books/1474154022m...,2900,3

In [37]:
book_rating_matrix = pd.pivot_table(books_info, index='user_id', values='rating', columns='book_id', fill_value=0)
book_rating_matrix

book_id,1,2,3,5,6,8,10,11,13,21,...,9854,9864,9865,9912,9913,9914,9915,9943,9957,9998
user_id,,,,,,,,,,,,,,,,,,,,,
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,4,0,0.0,0,0,0,0.0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
51,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
55,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
57,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
60,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
61,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53357,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53364,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53366,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53371,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53372,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53373,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53374,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53377,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53378,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53381,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53382,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53388,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53389,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53390,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53391,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53393,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53398,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53400,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53401,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53403,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53404,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53406,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53408,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53409,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53416,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53419,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53420,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53422,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53423,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0
53424,0,0,0,0,0,0,0,0,0,0,...,0,0,0.0,0,0,0,0.0,0,0,0

In [50]:
input_book = 1
book_entered = book_rating_matrix[input_book]
similar_to_book_entered = book_rating_matrix.corrwith(book_entered)
similar_to_book_entered = similar_to_book_entered.sort_values(ascending=False)
similar_to_book_entered = list(similar_to_book_entered[1:6])
similar_to_book_entered

[0.554059446282241,
 0.5076503273319484,
 0.48630481457534275,
 0.47852979204436885,
 0.4647022701119354]

In [ ]:
book_entered = books_data.loc[books_data['id'] == input_book]
print("Book entered is", book_entered['original_title'])